version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  kairos_api:
    image: kairos:latest
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=443
    ports:
      - "8074:8074"
    expose: 
      - "8074"
      - "443"
